export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export COLORTERM="truecolor"
export EDITOR="vim"
export PIP_REQUIRE_VIRTUALENV=true
export VIRTUAL_ENV_DISABLE_PROMPT=1
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#7A7A7A"

additional_paths=(
	~/.local/bin
	/opt/mssql-tools18/bin
)
for p in "${additional_paths[@]}"
do
	if [[ -d "$p" && ":$PATH:" != *":$p:"* ]] ; then
		PATH="$PATH:$p"
	fi
done
unset additional_paths
